version: '3'

services: 
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Xsw2zaq1
    volumes:
      - type: volume
        source: data
        target: /var/opt/mssql
volumes: 
  data: